### Requisição para cadastrar um aluno (create)
POST http://localhost:3000/student/create
Content-Type: application/json

{
    "password": "batata12",
    "name": "Nome do Aluno",
    "email": "Email@email.com"
}

### Requisição para listar todos os alunos (read)
GET http://localhost:3000/student/listar

### Requisição para buscar um aluno pelo id (read by id)
GET http://localhost:3000/student/1

### Requisição para atualizar um aluno pelo id (update by id)
PUT http://localhost:3000/student/4
Content-Type: application/json

{
    "password": "passwordNovo",
    "name": "Novo Aluno",
    "email": "NovoAluno@email.com"
}

### Requisição para deletar um aluno pelo id (delete by id)
DELETE http://localhost:3000/student/4